import { createGesture } from "./createGesture";

export const gestures = [
  createGesture({
    "name": "Yolo",
    "algorithm": "fingerpose",
    "models": "hands",
    "confidence": "7.75",
    "description": [
      [
        "addCurl",
        "Thumb",
        "NoCurl",
        1
      ],
      [
        "addDirection",
        "Thumb",
        "VerticalUp",
        1
      ],
      [
        "addCurl",
        "Index",
        "FullCurl",
        1
      ],
      [
        "addDirection",
        "Index",
        "DiagonalUpRight",
        1
      ],
      [
        "addDirection",
        "Index",
        "VerticalUp",
        0.7647058823529411
      ],
      [
        "addCurl",
        "Middle",
        "FullCurl",
        1
      ],
      [
        "addDirection",
        "Middle",
        "DiagonalUpRight",
        1
      ],
      [
        "addCurl",
        "Ring",
        "FullCurl",
        1
      ],
      [
        "addDirection",
        "Ring",
        "DiagonalUpRight",
        1
      ],
      [
        "addCurl",
        "Pinky",
        "NoCurl",
        1
      ],
      [
        "addDirection",
        "Pinky",
        "DiagonalUpRight",
        1
      ],
      [
        "setWeight",
        "Thumb",
        2
      ],
      [
        "setWeight",
        "Pinky",
        2
      ]
    ],
    "enabled": true
  }),
  createGesture({
    "name": "PewPew",
    "algorithm": "fingerpose",
    "models": "hands",
    "confidence": "7.75",
    "description": [
      [
        "addCurl",
        "Thumb",
        "NoCurl",
        1
      ],
      [
        "addDirection",
        "Thumb",
        "DiagonalUpRight",
        1
      ],
      [
        "addCurl",
        "Index",
        "NoCurl",
        1
      ],
      [
        "addDirection",
        "Index",
        "HorizontalRight",
        1
      ],
      [
        "addCurl",
        "Middle",
        "NoCurl",
        1
      ],
      [
        "addDirection",
        "Middle",
        "HorizontalRight",
        1
      ],
      [
        "addCurl",
        "Ring",
        "FullCurl",
        1
      ],
      [
        "addDirection",
        "Ring",
        "HorizontalRight",
        1
      ],
      [
        "addCurl",
        "Pinky",
        "FullCurl",
        1
      ],
      [
        "addDirection",
        "Pinky",
        "HorizontalRight",
        1
      ],
      [
        "setWeight",
        "Thumb",
        2
      ],
      [
        "setWeight",
        "Index",
        2
      ],
      [
        "setWeight",
        "Middle",
        2
      ]
    ]
  }),
  createGesture({
    "name": "callme",
    "algorithm": "fingerpose",
    "models": "hands",
    "confidence": "6.75",
    "description": [
      [
        "addCurl",
        "Thumb",
        "NoCurl",
        1
      ],
      [
        "addDirection",
        "Thumb",
        "VerticalUp",
        0.034482758620689655
      ],
      [
        "addDirection",
        "Thumb",
        "DiagonalUpRight",
        1
      ],
      [
        "addCurl",
        "Index",
        "FullCurl",
        1
      ],
      [
        "addDirection",
        "Index",
        "DiagonalUpRight",
        0.25
      ],
      [
        "addDirection",
        "Index",
        "HorizontalRight",
        1
      ],
      [
        "addCurl",
        "Middle",
        "FullCurl",
        1
      ],
      [
        "addDirection",
        "Middle",
        "HorizontalRight",
        1
      ],
      [
        "addCurl",
        "Ring",
        "FullCurl",
        1
      ],
      [
        "addDirection",
        "Ring",
        "HorizontalRight",
        1
      ],
      [
        "addCurl",
        "Pinky",
        "NoCurl",
        1
      ],
      [
        "addDirection",
        "Pinky",
        "HorizontalRight",
        1
      ],
      [
        "addDirection",
        "Thumb",
        "VerticalDown",
        0.034482758620689655
      ],
      [
        "addDirection",
        "Thumb",
        "DiagonalDownRight",
        1
      ],
      [
        "addDirection",
        "Index",
        "DiagonalDownRight",
        0.25
      ],
      [
        "setWeight",
        "Thumb",
        2
      ],
      [
        "setWeight",
        "Pinky",
        2
      ]
    ]
  }),
  createGesture({
    "name": "peace",
    "algorithm": "fingerpose",
    "models": "hands",
    "confidence": "7.25",
    "description": [
      [
        "addCurl",
        "Thumb",
        "HalfCurl",
        0.5
      ],
      [
        "addCurl",
        "Thumb",
        "NoCurl",
        1
      ],
      [
        "addDirection",
        "Thumb",
        "DiagonalUpRight",
        1
      ],
      [
        "addCurl",
        "Index",
        "NoCurl",
        1
      ],
      [
        "addDirection",
        "Index",
        "DiagonalUpLeft",
        1
      ],
      [
        "addDirection",
        "Index",
        "VerticalUp",
        0.5789473684210527
      ],
      [
        "addCurl",
        "Middle",
        "NoCurl",
        1
      ],
      [
        "addDirection",
        "Middle",
        "VerticalUp",
        1
      ],
      [
        "addDirection",
        "Middle",
        "DiagonalUpRight",
        0.5789473684210527
      ],
      [
        "addCurl",
        "Ring",
        "FullCurl",
        1
      ],
      [
        "addDirection",
        "Ring",
        "VerticalUp",
        1
      ],
      [
        "addDirection",
        "Ring",
        "DiagonalUpLeft",
        0.4117647058823529
      ],
      [
        "addDirection",
        "Ring",
        "DiagonalUpRight",
        0.35294117647058826
      ],
      [
        "addCurl",
        "Pinky",
        "FullCurl",
        1
      ],
      [
        "addDirection",
        "Pinky",
        "DiagonalUpRight",
        1
      ],
      [
        "addDirection",
        "Pinky",
        "VerticalUp",
        0.42105263157894735
      ],
      [
        "addDirection",
        "Pinky",
        "DiagonalUpLeft",
        0.15789473684210525
      ],
      [
        "setWeight",
        "Index",
        2
      ],
      [
        "setWeight",
        "Middle",
        2
      ]
    ]
  }),
  createGesture({
    "name": "okay",
    "algorithm": "fingerpose",
    "models": "hands",
    "confidence": "7",
    "description": [
      [
        "addCurl",
        "Thumb",
        "NoCurl",
        1
      ],
      [
        "addDirection",
        "Thumb",
        "HorizontalLeft",
        1
      ],
      [
        "addDirection",
        "Thumb",
        "DiagonalUpLeft",
        0.7647058823529411
      ],
      [
        "addCurl",
        "Index",
        "HalfCurl",
        1
      ],
      [
        "addDirection",
        "Index",
        "DiagonalUpLeft",
        1
      ],
      [
        "addDirection",
        "Index",
        "HorizontalLeft",
        0.30434782608695654
      ],
      [
        "addCurl",
        "Middle",
        "NoCurl",
        1
      ],
      [
        "addDirection",
        "Middle",
        "DiagonalUpLeft",
        1
      ],
      [
        "addCurl",
        "Ring",
        "NoCurl",
        1
      ],
      [
        "addDirection",
        "Ring",
        "VerticalUp",
        1
      ],
      [
        "addDirection",
        "Ring",
        "DiagonalUpLeft",
        0.5
      ],
      [
        "addCurl",
        "Pinky",
        "NoCurl",
        1
      ],
      [
        "addDirection",
        "Pinky",
        "DiagonalUpRight",
        1
      ],
      [
        "addDirection",
        "Pinky",
        "VerticalUp",
        0.36363636363636365
      ],
      [
        "addDirection",
        "Thumb",
        "DiagonalDownLeft",
        0.7647058823529411
      ],
      [
        "addDirection",
        "Index",
        "DiagonalDownLeft",
        1
      ],
      [
        "addDirection",
        "Middle",
        "DiagonalDownLeft",
        1
      ],
      [
        "addDirection",
        "Ring",
        "VerticalDown",
        1
      ],
      [
        "addDirection",
        "Ring",
        "DiagonalDownLeft",
        0.5
      ],
      [
        "addDirection",
        "Pinky",
        "DiagonalDownRight",
        1
      ],
      [
        "addDirection",
        "Pinky",
        "VerticalDown",
        0.36363636363636365
      ],
      [
        "setWeight",
        "Thumb",
        2
      ],
      [
        "setWeight",
        "Index",
        2
      ],
      [
        "setWeight",
        "Pinky",
        2
      ]
    ]
  }),
]